

export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const GET_STUDENTS = "GET_STUDENTS";
export const SEARCH_DATA = "SEARCH_DATA";
// async
export const ADD_NEW_SAGA = "ADD_NEW_SAGA"
export const LOGIN_SAGA_ACTION = "LOGIN_SAGA_ACTION";
export const SIGNUP_SAGA_ACTION = "SIGNUP_SAGA_ACTION";
export const AUTO_LOGIN_TOKEN_SAGA = "AUTO_LOGIN_TOKEN_SAGA";
export const GET_STUDENTS_SAGA  = "GET_STUDENTS_SAGA";
export const UPDATE_STUDENT_SAGA_DATA = "UPDATE_STUDENT_SAGA_DATA";
export const SEARCH_SAGA_DATA = "SEARCH_SAGA_DATA";
export const DELETE_SAGA_DATA = "DELETE_SAGA_DATA"
